name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: dotnet-version
      run: dotnet --version
    - name: pwd1
      run: pwd
    - name: ls1
      run: ls -a
    - name: cd to src
      run: cd /home/runner/work/AuthServer/AuthServer/src
    - name: pwd2
      run: pwd
    - name: ls2
      run: ls -a
    - name: Restore dependencies
      run: dotnet restore src/AuthServer.sln
    - name: Build
      run: dotnet build --no-restore src/AuthServer.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal src/AuthServer.sln
